### ISSUE TITLE
Does process/spawn daemonize a process?

### ISSUE THREAD

**Issue by crocket** [andrewchambers/janet-process#5]
I want to launch a process that's completely independent of the calling terminal. It seems to create a child process. But, I don't know whether it's immune to SIGHUP and independent of the calling process.

**Comment by andrewchambers** [comment]
It is not independent, to do this currently you can do something like:

```
(sh/shell-escape [...])
```
To form a command to pass to sh -c , in there you can run a background process or issue nohup and detatch it.

**Comment by crocket** [comment]
I found http://software.clapper.org/daemonize/ which is already a gentoo package.

**Comment by andrewchambers** [comment]
cool.

**Comment by crocket** [comment]
As far as I know, daemonizing a process is as simple as `setsid -f process >/dev/null 2>&1` Is it reproducible in process library?

**Comment by andrewchambers** [comment]
> daemonizing a process is as simple as setsid -f process >/dev/null 2>&1

You also need to double fork to prevent zombie processes, not really something I want to put into the process library.

**Comment by crocket** [comment]
Does `sh` create a daemonized process?

**Comment by andrewchambers** [comment]
What is it you are trying to accomplish?

**Comment by crocket** [comment]
I want to launch processes that do not print anything on the terminal emulator or die with it.
